### ISSUE TITLE
Can't setup ESP8266-12E

### ISSUE THREAD

**Issue by Albert245** [cpq/esputil#2]
I'm using esp8266-12E for this project but when I use esputil I've this issue:

> F:\Users\Nhat Pham\Downloads\esputil\windows>esputil -p COM12 flash 4m.hex monitor
> Using flash params 0
> Erasing 589824 bytes @ 0x370000error 6: Failed to act on received message
> 
> erase failed
> 
> F:\Users\Nhat Pham\Downloads\esputil\windows>esputil -p COM12 -fp 0x220 flash 4m.hex
> Using flash params 0x220
> Erasing 589824 bytes @ 0x370000error 6: Failed to act on received message
> 
> erase failed
> 
> F:\Users\Nhat Pham\Downloads\esputil\windows>esputil -p COM12 -fp 0x200 flash 4m.hex
> Using flash params 0x200
> Erasing 589824 bytes @ 0x370000error 6: Failed to act on received message
> 
> erase failed

Can anyone help me ?

**Comment by cpq** [comment]
Try `-fp 0x240`
