### ISSUE TITLE
esputil, Error reading chip ID

### ISSUE THREAD

**Issue by xiaolaba** [cpq/esputil#5]
hi, this is not be able to burn the chip, win10 used, esp32-WROOM module, any hints, 
thanks

the same hex is used esptool.exe to burn the same chip, it was ok.

dosbox and console output as following,

xiao$ esputil mkhex 0x1000 ESP32_40MHZ_counter.ino.bootloader.bin 0x8000 ESP32_40MHZ_counter.ino.partitions.bi
n 0xe000 boot_app0.bin 0x10000 ESP32_40MHZ_counter.ino.bin  1>firmware.hex

xiao$ rem esputil -v -b 921600 -p COM5 -fp 0x220 flash 4096 firmware.hex

xiao$ esputil -v -b 921600 -p COM5 -fp 0x220 flash 0xe000 boot_app0.bin
SYNC [44 bytes]
0000  00 08 24 00 00 00 00 00 07 07 12 20 55 55 55 55  ..$........ UUUU
0010  55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55  UUUUUUUUUUUUUUUU
0020  55 55 55 55 55 55 55 55 55 55 55 55              UUUUUUUUUUUU

SYNC [44 bytes]
0000  00 08 24 00 00 00 00 00 07 07 12 20 55 55 55 55  ..$........ UUUU
0010  55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55  UUUUUUUUUUUUUUUU
0020  55 55 55 55 55 55 55 55 55 55 55 55              UUUUUUUUUUUU

SYNC [44 bytes]
0000  00 08 24 00 00 00 00 00 07 07 12 20 55 55 55 55  ..$........ UUUU
0010  55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55  UUUUUUUUUUUUUUUU
0020  55 55 55 55 55 55 55 55 55 55 55 55              UUUUUUUUUUUU

SYNC [44 bytes]
0000  00 08 24 00 00 00 00 00 07 07 12 20 55 55 55 55  ..$........ UUUU
0010  55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55  UUUUUUUUUUUUUUUU
0020  55 55 55 55 55 55 55 55 55 55 55 55              UUUUUUUUUUUU

SYNC [44 bytes]
0000  00 08 24 00 00 00 00 00 07 07 12 20 55 55 55 55  ..$........ UUUU
0010  55 55 55 55 55 55 55 55 55 55 55 55 55 55 55 55  UUUUUUUUUUUUUUUU
0020  55 55 55 55 55 55 55 55 55 55 55 55              UUUUUUUUUUUU

--SLIP_RESPONSE: [12 bytes]
0000  01 08 04 00 12 20 55 55 00 00 00 00              ..... UU....

READ_REG [12 bytes]
0000  00 0a 04 00 00 00 00 00 00 10 00 40              ...........@

Error reading chip ID

xiao$ pause
Press any key to continue . . .

**Comment by cpq** [comment]
@xiaolaba use low baud rate - don't specify `-b 921600 `
